/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package revature.com;

import io.javalin.Javalin;
import revature.com.controllers.ReimbursementController;
import revature.com.controllers.UserController;
import revature.com.dao.IReimbursementDao;
import revature.com.dao.IUserDao;
import revature.com.dao.ReimbursementDaoJDBC;
import revature.com.dao.UserDaoJDBC;
import revature.com.models.Reimbursement;
import revature.com.services.ReimbursementService;
import revature.com.services.UserService;

public class Drive {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        IUserDao ud = new UserDaoJDBC();

        IReimbursementDao rd = new ReimbursementDaoJDBC();

        UserService us = new UserService(ud);

        ReimbursementService rs = new ReimbursementService(rd);

        UserController uc = new UserController(us);

        ReimbursementController rc = new ReimbursementController(rs);

        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });

        server.start(8080);
    }
}
