/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package revature.com;

import io.javalin.Javalin;
import revature.com.controllers.ReimbursementController;
import revature.com.controllers.UserController;
import revature.com.dao.IReimbursementDao;
import revature.com.dao.IUserDao;
import revature.com.dao.ReimbursementDaoJDBC;
import revature.com.dao.UserDaoJDBC;
import revature.com.models.Reimbursement;
import revature.com.services.ReimbursementService;
import revature.com.services.UserService;

import static io.javalin.apibuilder.ApiBuilder.*;
import static io.javalin.apibuilder.ApiBuilder.post;

public class Drive {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        IUserDao ud = new UserDaoJDBC();

        IReimbursementDao rd = new ReimbursementDaoJDBC();

        UserService us = new UserService(ud);

        ReimbursementService rs = new ReimbursementService(rd);

        UserController uc = new UserController(us);

        ReimbursementController rc = new ReimbursementController(rs);



        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });

        server.before(ctx -> ctx.header("Access-Control-Allow-Credentials", "true"));
        server.before(ctx -> ctx.header("Access-Control-Expose-Headers", "*"));

        server.routes(()-> {
            path("users", () -> {

                post("/register", uc.handleRegisterUser);
                post("/login", uc.handleLoginUser);
                get("/logout", uc.handleLogout);
                get("/viewInfo", uc.handleShowUserByUserName);
                post("/update", uc.handleUpdateUser);

                // Manager only
                get("/showAllByManager", uc.handlerShowAllByManager);

            });
            path("reimbursement", () -> {
                post("/sendRequest", rc.handlerReimbursementRequest);
                get("/viewPendingReimbursement", rc.handlerViewPendingReimbursement);
                get("/viewResolvedReimbursement", rc.handlerViewResolvedReimbursement);

                // Manager only
                post("/approveOrDeny", rc.handlerApproveReimbursement);
                get("/showAllPendingByManager", rc.handlerViewAllPendingRequests);
                get("/showAllResolvedByManager", rc.handlerViewAllResolvedRequests);
                get("/showSpecificEmployee", rc.handlerViewAllSpecificRequests);


            });
        });
        server.start(8080);
    }
}
