/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.controller.GroceryController;
import com.revature.dao.IListDao;
import com.revature.dao.ListDaoJDBC;
import com.revature.service.GroceryService;
import io.javalin.Javalin;

import static io.javalin.apibuilder.ApiBuilder.*;

public class App {

    public static void main(String[] args) {

        IListDao ild = new ListDaoJDBC();
        GroceryService gs = new GroceryService(ild);
        GroceryController gc = new GroceryController(gs);

        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });

        server.routes(() -> {
            path("list", () -> {
                //takes in json, returns id as string
                post("/create", gc.handleCreate);
                //takes in json, returns string
                post("/read", gc.handleRead);
                //takes in json
                put("/", gc.handleUpdate);
                //takes in nothing
                delete("/{id}", gc.handleDelete);
                //takes in nothing, returns json
                get("/showall", gc.handleReadAllListItems);
            });
        });

        server.start(8000);
    }
}
