/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package revature.com;

import org.junit.Test;
import revature.com.models.RegisterUsers;
import revature.com.models.Users;
import revature.com.services.*;
import revature.com.dao.*;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import static org.junit.Assert.*;

public class AppTest {
    @Mock
    static IUserDao ud;

    @InjectMocks
    static UserService us;



    @Test
    public void validLoginCredentialsTest(){
        Users user = new Users(1, "Username", "password", "firstName", "lastName", "test@mail.com", 0);
        when(ud.getUserInfo(any())).thenReturn(user);


        Users loggedIn = us.loginUser("Username", "password");
        verify(ud).getUserInfo(any());

        assertEquals("The username of user should be 'Username'", "Username", loggedIn.getUsername());
    }
}
