/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package revature.com;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.javalin.Javalin;
import revature.com.controllers.GroceryItemsController;
import revature.com.dao.GroceryItemsDaoJDBC;
import revature.com.dao.IGroceryItemsDao;

import revature.com.services.GroceryItemsServices;

import static io.javalin.apibuilder.ApiBuilder.*;

public class Drive {


    public static void main(String[] args) {

        IGroceryItemsDao gd = new GroceryItemsDaoJDBC();

        GroceryItemsServices gs = new GroceryItemsServices(gd);

        GroceryItemsController gc = new GroceryItemsController(gs);
        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });

        server.routes(()-> {
            path("grocery", () -> {

                post("/create", gc.handleCreateItems);
                get("/show", gc.handlerShowAll);
                delete("/delete", gc.handlerDelete);
                post("/update", gc.handlerUpdatePrice);


            });



        });
        // Run server
        server.start(8080);
    }
}
