/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;
import com.revature.controller.PersonController;
import com.revature.dao.IPersonDao;
import com.revature.dao.PersonDAO;

import com.revature.service.PersonServices;
import com.revature.utils.ConnectionUtil;
import com.revature.utils.DBUtils;
import io.javalin.Javalin;

import java.sql.Connection;

import static io.javalin.apibuilder.ApiBuilder.path;
import static io.javalin.apibuilder.ApiBuilder.post;

public class DaoDriver {

    public static void main(String[] args) {

        Connection con = ConnectionUtil.getConnectionUtil().getConnection();

        IPersonDao pd = new PersonDAO();
        PersonServices ps = new PersonServices(pd);
        PersonController pc = new PersonController(ps);

        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });

        server.routes(() -> {
            path("person", () -> {
                post("/createPerson", pc.handleCreate);
            });
        });

        //Run the following code at least once, after the initial DB setup you no longer need to run it,
        //Or you could run it each time to start out with a fresh slate each time
        DBUtils.setupDB(con);

        server.start(8000);
    }
}
